### ISSUE TITLE
QueueHandler not working with LokiHandler

### ISSUE THREAD

**Issue by averri** [GreyZmeem/python-logging-loki#27]
This code, gotten from the project examples, does not work. It does not produce any logs on Loki:

```python
import logging.handlers
import logging_loki
from multiprocessing import Queue

queue = Queue(-1)

handler = logging.handlers.QueueHandler(queue)

handler_loki = logging_loki.LokiHandler(
    url="http://localhost:3100/loki/api/v1/push",
    tags={"app": "none", "job": "testing-loki", "env": "dev"},
    version="1",
)

logging.handlers.QueueListener(queue, handler_loki)

logger = logging.getLogger("my-logger")
logger.addHandler(handler)

if __name__ == '__main__':
    logger.info("Hello, world")
    logger.error("Something wrong...")
```

You may start Loki using Docker Compose `docker-compose up -d` in the same directory as the following `docker-compose.yml`file:

```yaml
version: "3.7"
services:
  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3100:3100"
```
